// <auto-generated />
using System;
using LayupPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LayupPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    partial class HistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LayupPulse.Infrastructure.Persistence.AlarmRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClearedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductionRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaisedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionRunId");

                    b.HasIndex("RaisedAtUtc");

                    b.ToTable("Alarms", (string)null);
                });

            modelBuilder.Entity("LayupPulse.Infrastructure.Persistence.ProductionRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AlarmCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageCompactionForceNewtons")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageFeedRateMillimetersPerSecond")
                        .HasColumnType("REAL");

                    b.Property<double>("AveragePressureBar")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageTemperatureCelsius")
                        .HasColumnType("REAL");

                    b.Property<double>("CompletionPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumProcessHealthPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("PartReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinalStatus");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("ProductionRuns", (string)null);
                });

            modelBuilder.Entity("LayupPulse.Infrastructure.Persistence.TelemetryAggregateRecord", b =>
                {
                    b.Property<Guid>("ProductionRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BucketStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageCompactionForceNewtons")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageFeedRateMillimetersPerSecond")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageHeaterTemperatureCelsius")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageMaterialPressureBar")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageProcessHealthPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("EndOfBucketCycleProgressPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumCompactionForceNewtons")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumHeaterTemperatureCelsius")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumMaterialPressureBar")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumCompactionForceNewtons")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumHeaterTemperatureCelsius")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumMaterialPressureBar")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumProcessHealthPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductionRunId", "BucketStartedAtUtc");

                    b.ToTable("TelemetryAggregates", (string)null);
                });

            modelBuilder.Entity("LayupPulse.Infrastructure.Persistence.AlarmRecord", b =>
                {
                    b.HasOne("LayupPulse.Infrastructure.Persistence.ProductionRunRecord", "ProductionRun")
                        .WithMany("Alarms")
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("LayupPulse.Infrastructure.Persistence.TelemetryAggregateRecord", b =>
                {
                    b.HasOne("LayupPulse.Infrastructure.Persistence.ProductionRunRecord", "ProductionRun")
                        .WithMany("TelemetryAggregates")
                        .HasForeignKey("ProductionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("LayupPulse.Infrastructure.Persistence.ProductionRunRecord", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("TelemetryAggregates");
                });
#pragma warning restore 612, 618
        }
    }
}
